# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dET9rLL7vBGQnxMhvhDH0VVTdzzqn7jp
"""

import matplotlib.pyplot as plt
import pandas as pd

"""**1. Load data**"""

import pandas as pd

import pandas as pd
df_data = pd.read_csv('/content/Fixed data demo.csv')
df_data.head()

df_data.info()

"""**2. Analytics**"""

df_data.loc[df_data.Churn=='No','Churn'] = 0
df_data.loc[df_data.Churn=='Yes','Churn'] = 1

df_data['Churn'] = df_data['Response'].apply(lambda x: 1 if x == 'Yes' else 1)
df_data.head()

import plotly.graph_objects as go
import plotly.offline as pyoff

# Calculate Churn Rate (%)
churn_rate_female = (churned_female_customers / total_female_customers) * 100
churn_rate_male = (churned_male_customers / total_male_customers) * 100

print(f"Churn Rate for Female Customers: {churn_rate_female:.2f}%")
print(f"Churn Rate for Male Customers: {churn_rate_male:.2f}%")

# Calculate Churn Rate as a proportion
churn_rate_female = (churned_female_customers / total_female_customers)
churn_rate_male = (churned_male_customers / total_male_customers)

print(f"Churn Rate for Female Customers: {churn_rate_female:.4f}")
print(f"Churn Rate for Male Customers: {churn_rate_male:.4f}")

import plotly.graph_objects as go
import plotly.offline as pyoff

# Use the provided churn rates
churn_rate_female = 0.1642
churn_rate_male = 0.1149

df_plot = pd.DataFrame({'Gender': ['FEMALE', 'MALE'], 'Churn': [churn_rate_female, churn_rate_male]})

plot_data = [
    go.Bar(
        x=df_plot['Gender'],
        y=df_plot['Churn'],
        width = [0.5, 0.5],
        marker=dict(
        color=['green', 'blue'])
    )
]
plot_layout = go.Layout(
        xaxis={"type": "category"},
        yaxis={"title": "Churn Rate"},
        title='Gender',
        plot_bgcolor  = 'rgb(243,243,243)',
        paper_bgcolor  = 'rgb(243,243,243)',
    )
fig = go.Figure(data=plot_data, layout=plot_layout)
pyoff.iplot(fig)